### ISSUE TITLE
support for txt vectors with first descriptive line

### ISSUE THREAD

**Issue by annargrs** [undertherain/vsmlib#1]
Importing text-format vectors should check for lines that are irregular length and ignore them / read them as comments. E.g. Levy et al.'s dependency-based embeddings indicate vocab size on the first line.

**Comment by undertherain** [comment]
can you give a link to such vectors?

**Comment by annargrs** [comment]
http://u.cs.biu.ac.il/~yogo/data/syntemb/deps.words.bz2

**Comment by undertherain** [comment]
those starts with the first word "the".
you mentioned some other example, do you have link?

**Comment by annargrs** [comment]
https://drive.google.com/file/d/0BwF2zP8bVaQrc2ptLXhkTmx5SE0/view?usp=sharing

**Comment by undertherain** [comment]
ModelDense.load_from_text now automatically detects header
