### ISSUE TITLE
How to access the corpus used to train the pre-trained embeddings? 

### ISSUE THREAD

**Issue by alvations** [undertherain/vsmlib#10]
On https://vsmlib.readthedocs.io/en/latest/tutorial/getting_vectors.html#pre-trained-vsms there's a link to *download the source corpus with which you can train other VSMs for fair comparison.* 

But the link led to https://my.pcloud.com/publink/show?code=XZYcQV7ZR67964yEkEJhgHaM273JjptIUEpX

> Pursuant to pCloud’s Terms of Service, access to this file has been disabled.

Is there a place where you can share the source corpus again?

**Comment by annargrs** [comment]
Oops, thanks for letting us know - that's shouldn't be happening. I've written to pcloud support, will respond as soon as they do. 

In the meanwhile, the work on vsmlib is now continued in the vecto project, check out this repo: https://github.com/vecto-ai/vecto

**Comment by annargrs** [comment]
fixed this, links are working again.

**Comment by alvations** [comment]
Thanks @annargrs!!
