### ISSUE TITLE
Make BATS Test Runner runable from code

### ISSUE THREAD

**Issue by villmow** [undertherain/vsmlib#9]
I want to start the test runner for the bats dataset from code. Right now it is only possible by setting some module variables (`vsmlib.benchmark.analogy.analogy.m` and `vsmlib.benchmark.analogy.analogy.options`) and afterwards calling `run_all(dataset_path)`.

Why not change the signature of that method from
```python
def run_all(name_dataset)
```
to 
```python
def run_all(model, dataset_path, result_path, method, normalize, exclude):
    ....
```
?

**Comment by annargrs** [comment]
I guess that's a use case question. If you want to just evaluate one set of embeddings, the way you propose is indeed faster and more interactive. We developed this while evaluating dozens of embeddings, though, so our config files were always huge. 

I'm running into the same problem elsewhere now, and I'm not sure what would be the best approach to handle both use cases. It'd be cool to maintain the interactivity, but with over 5 parameters things just become unreadable.

**Comment by undertherain** [comment]
In general yes, something like that would be reasonable. 
One issue is that some parameters are specific to particular analogy solving methods and those methods keep being added. So having them all in function signature would not work, passing something like kwargs to some programmatic entry point might work though. 
We are working more or less in that direction, stay tuned ;)

**Comment by undertherain** [comment]
@villmow please check current run() method in analogy.py, hope it's what you are looking for
